### ISSUE TITLE
nand.gq 域名被收回导致无法访问网页版

### ISSUE THREAD

**Issue by ZYGLQexplorer** [iTXTech/FlashDetector#4]
nand.gq 域名被收回导致无法访问网页版，请问后续还有维护计划吗，是否需要域名捐助

**Comment by PeratX** [comment]
https://fm.itxtech.org

**Comment by PeratX** [comment]
现在MPTool很难获取，后面的更新计划未知，欢迎社区贡献！

**Comment by PeratX** [comment]
https://github.com/iTXTech/FlashDetector/commit/2e30f53488845291d9f08e71fbb7678e25f42fd7

**Comment by barryblueice** [comment]
用阿里云函数应用搭建了一个：[nand.barryblueice.cn](http://nand.barryblueice.cn/)，速度可能会有些慢。
